### ISSUE TITLE
a station but it doesn't work

### ISSUE THREAD

**Issue by fezo76** [amaximus/radioactivity_hu#5] opened 2022-12-12 08:30 UTC
Hi! I tried Székesfehérvár as a station but it doesn't work. If "unavailable" is displayed in the filter states line. I tried several other cities, they work.
Thanks!

**Comment by amaximus** [comment] 2022-12-12 09:05
Hi, can you paste the sensor configuration? Try putting the station name into single quotes.

**Comment by fezo76** [comment] 2022-12-12 09:21
###################################
### RADIOAKTIVITAS
###################################

 - platform: radioactivity_hu
   station: "Székesfehérvár"
   name: Radioaktivitas

**Comment by amaximus** [comment] 2022-12-12 11:38
The issue is that although on the page from README the city has a measurement value,  the integration takes data from https://www.katasztrofavedelem.hu/application/uploads/cache/hattersugarzas/RAD.json and processes that one. 
Although the JSON file has a quite recent timestamp at the beginning, there is a discrepancy between the data presented on the web page and the one provided in the JSON file. For example the JSON file currently doesn't show measurement data for Székesfehérvár.

Anyway I released a change for strict measurement data checking, which in turn will not resolve the missing data issue.

**Comment by fezo76** [comment] 2022-12-12 19:47
I understand and thank you for the quick reply.

**Comment by fezo76** [comment] 2022-12-14 07:54
Hi!
I looked at the JSON file and there are 2 Székesfehérvárs in it. maybe that's why the value doesn't appear?

**Comment by amaximus** [comment] 2022-12-14 08:20
Good catch, let me add a fix for this. I'll let you know soon.

**Comment by amaximus** [comment] 2022-12-14 08:56
I just pushed a release (0.3.2) handling multiple occurences of the station in JSON.

Please update the integration and get back to me with results.

**Comment by fezo76** [comment] 2022-12-14 13:01
thanks for the quick fix, it works!

**Closed as completed** 2022-12-14 18:46 UTC
